FROM mongo:latest

# Copy the JSON files and the init script to the container
COPY ./db/*.json /docker-entrypoint-initdb.d/
COPY ./mongo-init.sh /docker-entrypoint-initdb.d/

# Make sure the init script is executable
RUN chmod +x /docker-entrypoint-initdb.d/mongo-init.sh
